import type { UiLang } from "@/features/patient-home/welcome";

export const STEPS: Record<UiLang, string[]> = {
  ru: ["Анкета", "Программа", "Терапевт", "План врача", "Подготовка", "Результаты", "Повторы"],
  kz: ["Сауалнама", "Бағдарлама", "Терапевт", "Дәрігер жоспары", "Дайындық", "Нәтижелер", "Қайталау"],
};

export const CABINET_COPY = {
  ru: {
    hello: (name: string) => `Добрый день, ${name}`,
    // nav
    tabOverview: "Обзор",
    tabVisits: "Записи",
    tabPrep: "Подготовка",
    tabResults: "Результаты",
    newCheckup: "Новый чек-ап",
    toHome: "На главную",
    logout: "Выйти",
    language: "Язык",
    programFallback: "Чек-ап",
    // next step
    nextStep: "Следующий шаг",
    // appointment / program
    appointment: "Ближайший приём",
    noAppointment: "Приём ещё не назначен",
    program: "Программа",
    programUnknown: "Программа уточняется на приёме",
    programNote: "Предварительный выбор. Состав подтверждает врач.",
    // prep
    prep: "Подготовка",
    prepEmpty: "Появится после того, как врач подтвердит план.",
    due: "Срок",
    dueUnknown: "срок уточняется",
    // results
    results: "Результаты",
    resultsEmpty: "Результатов пока нет.",
    follow: "Повторы и задачи",
    followEmpty: "Назначений от врача пока нет.",
    source: "Фрагмент источника",
    review: { pending: "Ждёт разбора врачом", reviewed: "Врач разобрал" } as Record<string, string>,
    // visits
    visitsEmpty: "Записей пока нет. Запишитесь к терапевту после подбора программы.",
    // sign-in
    signInTitle: "Войдите в кабинет",
    signInBody: "Здесь будут ваши записи, подготовка, результаты и повторы.",
    signIn: "Войти",
    // empty (logged in, no cases)
    emptyTitle: "Начните свой чек-ап",
    emptyBody: "Пройдите короткий подбор и запишитесь к терапевту.",
    demo: "Информация в кабинете не заменяет консультацию врача.",
    welcome: (phone: string) => `Кабинет создан. В следующий раз входите по номеру ${phone}.`,
    welcomeDismiss: "Понятно",
    appt: {
      demo_confirmed: "Подтверждено",
      clinic_confirmed: "Подтверждено",
      clinic_request_pending: "Заявка отправлена",
    } as Record<string, string>,
    stageNext: {
      questionnaire_saved: ["Выберите программу", "Анкета сохранена. Посмотрите предварительный подбор."],
      package_selected: ["Запишитесь к терапевту", "Программа выбрана — осталось выбрать время приёма."],
      therapist_booking_requested: ["Ждём подтверждения клиники", "Заявка на приём отправлена координатору."],
      therapist_booking_confirmed: ["Приходите на приём", "Терапевт уточнит программу и подтвердит план."],
      consultation_completed: ["Ждём план врача", "Подготовка и день обследований появятся после плана."],
      physician_plan_confirmed: ["Подготовьтесь к обследованиям", "Отметьте пункты подготовки."],
      preparation_in_progress: ["Подготовьтесь к обследованиям", "Отметьте пункты подготовки."],
      results_available: ["Результаты готовы", "Врач разберёт их и назначит следующие шаги."],
      follow_up_planned: ["Повторы по плану врача", "Сроки, которых нет в плане, остаются «уточняется»."],
    } as Record<string, [string, string]>,
    ctaIntake: "Пройти подбор",
    ctaPrep: "К подготовке",
    ctaResults: "К результатам",
  },
  kz: {
    hello: (name: string) => `Қайырлы күн, ${name}`,
    tabOverview: "Шолу",
    tabVisits: "Жазылулар",
    tabPrep: "Дайындық",
    tabResults: "Нәтижелер",
    newCheckup: "Жаңа чек-ап",
    toHome: "Басты бетке",
    logout: "Шығу",
    language: "Тіл",
    programFallback: "Чек-ап",
    nextStep: "Келесі қадам",
    appointment: "Жақын қабылдау",
    noAppointment: "Қабылдау әлі тағайындалмаған",
    program: "Бағдарлама",
    programUnknown: "Бағдарлама қабылдауда нақтыланады",
    programNote: "Алдын ала таңдау. Құрамын дәрігер бекітеді.",
    prep: "Дайындық",
    prepEmpty: "Дәрігер жоспарды бекіткеннен кейін пайда болады.",
    due: "Мерзім",
    dueUnknown: "мерзімі нақтыланады",
    results: "Нәтижелер",
    resultsEmpty: "Әзірге нәтиже жоқ.",
    follow: "Қайталау мен тапсырмалар",
    followEmpty: "Дәрігер тағайындаулары әзірге жоқ.",
    source: "Дереккөз үзіндісі",
    review: { pending: "Дәрігер қарауын күтуде", reviewed: "Дәрігер қарады" } as Record<string, string>,
    visitsEmpty: "Әзірге жазылу жоқ. Бағдарламаны таңдап, терапевтке жазылыңыз.",
    signInTitle: "Кабинетке кіріңіз",
    signInBody: "Мұнда жазылулар, дайындық, нәтижелер және қайталаулар болады.",
    signIn: "Кіру",
    emptyTitle: "Чек-ап бастаңыз",
    emptyBody: "Қысқа іріктеуден өтіп, терапевтке жазылыңыз.",
    demo: "Кабинеттегі ақпарат дәрігер кеңесін алмастырмайды.",
    welcome: (phone: string) => `Кабинет ашылды. Келесі жолы ${phone} нөмірімен кіріңіз.`,
    welcomeDismiss: "Түсінікті",
    appt: {
      demo_confirmed: "Расталды",
      clinic_confirmed: "Расталды",
      clinic_request_pending: "Өтінім жіберілді",
    } as Record<string, string>,
    stageNext: {
      questionnaire_saved: ["Бағдарламаны таңдаңыз", "Сауалнама сақталды. Алдын ала іріктеуді қараңыз."],
      package_selected: ["Терапевтке жазылыңыз", "Бағдарлама таңдалды — қабылдау уақытын таңдаңыз."],
      therapist_booking_requested: ["Клиника растауын күтеміз", "Қабылдауға өтінім үйлестірушіге жіберілді."],
      therapist_booking_confirmed: ["Қабылдауға келіңіз", "Терапевт бағдарламаны нақтылап, жоспарды бекітеді."],
      consultation_completed: ["Дәрігер жоспарын күтеміз", "Дайындық жоспардан кейін пайда болады."],
      physician_plan_confirmed: ["Тексеруге дайындалыңыз", "Дайындық тармақтарын белгілеңіз."],
      preparation_in_progress: ["Тексеруге дайындалыңыз", "Дайындық тармақтарын белгілеңіз."],
      results_available: ["Нәтижелер дайын", "Дәрігер оларды қарап, келесі қадамдарды тағайындайды."],
      follow_up_planned: ["Дәрігер жоспары бойынша қайталау", "Жоспарда жоқ мерзімдер «нақтыланады» болып қалады."],
    } as Record<string, [string, string]>,
    ctaIntake: "Іріктеуден өту",
    ctaPrep: "Дайындыққа",
    ctaResults: "Нәтижелерге",
  },
} as const;
