import type { UiLang } from "@/features/patient-home/welcome";

/** RU/KZ strings for the redesigned booking flow. */
export const BOOKING_COPY = {
  ru: {
    // therapist card
    therapistName: "Врач-терапевт",
    therapistRole: "Первичный приём · 30 мин",
    programFallback: "Чек-ап",
    // calendar
    pickDay: "Выберите день",
    weekdays: ["Пн", "Вт", "Ср", "Чт", "Пт", "Сб", "Вс"],
    prevMonth: "Предыдущий месяц",
    nextMonth: "Следующий месяц",
    // time column
    time: "Время",
    pickDayFirst: "Сначала выберите день в календаре.",
    loading: "Загружаем время…",
    noSlots: "На этот день нет свободного времени. Выберите другой день.",
    retry: "Повторить",
    busy: "занято",
    morning: "Утро",
    afternoon: "День",
    evening: "Вечер",
    // contact form
    contact: "Контакты и личный кабинет",
    contactHelper:
      "По этому номеру создадим личный кабинет: запись, подготовка и результаты будут в нём. Вход — по номеру и коду из СМС.",
    loggedInNote: "Запись появится в вашем кабинете.",
    name: "Имя",
    namePh: "Как к вам обращаться",
    phone: "Телефон",
    errNameRequired: "Укажите имя",
    errPhoneInvalid: "Введите номер: +7 и 10 цифр",
    // consent
    consentTransferTitle: "Согласие на передачу в клинику",
    consentTransferBody: "Передаём имя, телефон и выбранный слот в клинику для записи. Обязательно.",
    consentReminderTitle: "Напомнить по СМС за день до приёма",
    consentReminderBody: "Пришлём напоминание накануне визита. По желанию.",
    consentVersion: (v: string) => `Версия текста согласия: ${v}`,
    // summary + submit
    summaryDate: "Дата",
    summaryTime: "Время",
    summaryProgram: "Программа",
    summaryPrice: "Стоимость",
    priceUnknown: "Стоимость уточняется в клинике",
    notPicked: "не выбрано",
    submit: "Записаться",
    submitting: "Отправляем…",
    // errors
    errSlot: "Выберите свободное время",
    errConsent: "Нужно согласие на передачу в клинику",
    errContact: "Укажите имя и телефон",
    errNoSubmission: "Сначала заполните анкету и выберите программу",
    errConfig: "Данные клиники ещё загружаются",
    errConflict: "Это время уже заняли. Выберите другое.",
    errGeneric: "Не удалось записаться. Попробуйте ещё раз.",
    // no-nav-state gate
    gateTitle: "Сначала подберём программу",
    gateBody: "Чтобы записаться к терапевту, пройдите короткий подбор чек-апа — так приём будет полезнее.",
    gateCta: "Пройти подбор",
    // unavailable
    unavailableTitle: "Запись недоступна",
    toHome: "На главную",
    // success
    successConfirmed: "Вы записаны",
    successPending: "Заявка отправлена",
    bodyConfirmed: "Запись подтверждена. Детали — в вашем личном кабинете.",
    bodyPending: "Заявка ждёт подтверждения клиники. Мы сообщим, когда приём подтвердят.",
    checkAccount: "Личный кабинет создан",
    checkQuestionnaire: "Анкета передана терапевту",
    checkReminder: "Напомним по СМС",
    addCalendar: "Добавить в календарь",
    openCabinet: "Открыть личный кабинет",
    footerNote: "Информация не заменяет консультацию врача.",
  },
  kz: {
    therapistName: "Дәрігер-терапевт",
    therapistRole: "Алғашқы қабылдау · 30 мин",
    programFallback: "Чек-ап",
    pickDay: "Күнді таңдаңыз",
    weekdays: ["Дс", "Сс", "Ср", "Бс", "Жм", "Сн", "Жс"],
    prevMonth: "Алдыңғы ай",
    nextMonth: "Келесі ай",
    time: "Уақыт",
    pickDayFirst: "Алдымен күнтізбеден күнді таңдаңыз.",
    loading: "Уақыт жүктелуде…",
    noSlots: "Бұл күні бос уақыт жоқ. Басқа күнді таңдаңыз.",
    retry: "Қайталау",
    busy: "бос емес",
    morning: "Таң",
    afternoon: "Күндіз",
    evening: "Кеш",
    contact: "Байланыс және жеке кабинет",
    contactHelper:
      "Осы нөмір бойынша жеке кабинет ашамыз: жазылу, дайындық пен нәтижелер сонда болады. Кіру — нөмір мен СМС коды арқылы.",
    loggedInNote: "Жазылу кабинетіңізде көрінеді.",
    name: "Аты",
    namePh: "Сізге қалай жүгінеміз",
    phone: "Телефон",
    errNameRequired: "Атыңызды көрсетіңіз",
    errPhoneInvalid: "Нөмірді енгізіңіз: +7 және 10 сан",
    consentTransferTitle: "Клиникаға беруге келісім",
    consentTransferBody: "Жазылу үшін аты, телефоны мен таңдалған уақытты клиникаға береміз. Міндетті.",
    consentReminderTitle: "Қабылдаудан бір күн бұрын СМС арқылы еске салу",
    consentReminderBody: "Визит қарсаңында еске салу жібереміз. Қалауыңызша.",
    consentVersion: (v: string) => `Келісім мәтінінің нұсқасы: ${v}`,
    summaryDate: "Күні",
    summaryTime: "Уақыты",
    summaryProgram: "Бағдарлама",
    summaryPrice: "Құны",
    priceUnknown: "Құны клиникада нақтыланады",
    notPicked: "таңдалмаған",
    submit: "Жазылу",
    submitting: "Жіберілуде…",
    errSlot: "Бос уақытты таңдаңыз",
    errConsent: "Клиникаға беруге келісім қажет",
    errContact: "Аты мен телефонды көрсетіңіз",
    errNoSubmission: "Алдымен сауалнаманы толтырып, бағдарламаны таңдаңыз",
    errConfig: "Клиника деректері әлі жүктелуде",
    errConflict: "Бұл уақытты алып қойды. Басқасын таңдаңыз.",
    errGeneric: "Жазылу мүмкін болмады. Қайталап көріңіз.",
    gateTitle: "Алдымен бағдарламаны таңдаймыз",
    gateBody: "Терапевтке жазылу үшін қысқа чек-ап іріктеуінен өтіңіз — сонда қабылдау пайдалы болады.",
    gateCta: "Іріктеуден өту",
    unavailableTitle: "Жазылу қолжетімсіз",
    toHome: "Басты бетке",
    successConfirmed: "Сіз жазылдыңыз",
    successPending: "Өтінім жіберілді",
    bodyConfirmed: "Жазылу расталды. Толығырақ — жеке кабинетіңізде.",
    bodyPending: "Өтінім клиника растауын күтуде. Қабылдау расталғанда хабарлаймыз.",
    checkAccount: "Жеке кабинет ашылды",
    checkQuestionnaire: "Анкета терапевтке берілді",
    checkReminder: "СМС арқылы еске саламыз",
    addCalendar: "Күнтізбеге қосу",
    openCabinet: "Жеке кабинетті ашу",
    footerNote: "Ақпарат дәрігер кеңесін алмастырмайды.",
  },
} as const;

export type BookingCopy = (typeof BOOKING_COPY)[UiLang];
